# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 06:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('sourcetype', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usercode', models.CharField(blank=True, default=b'2017-04-12 14:37:50.164787', max_length=128, unique=True)),
                ('photoBucket', models.CharField(blank=True, max_length=32, null=True)),
                ('photoKey', models.CharField(blank=True, max_length=64, null=True)),
                ('cardBucket', models.CharField(blank=True, max_length=32, null=True)),
                ('cardKey', models.CharField(blank=True, max_length=64, null=True)),
                ('wechat', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, db_index=True, help_text='\u59d3\u540d', max_length=128, null=True)),
                ('nameE', models.CharField(blank=True, db_index=True, help_text='name', max_length=128, null=True)),
                ('mobileAreaCode', models.CharField(blank=True, default='86', max_length=3, null=True)),
                ('mobile', models.CharField(blank=True, db_index=True, help_text='\u624b\u673a', max_length=32, null=True)),
                ('company', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, default='description', help_text='\u7b80\u4ecb')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='\u90ae\u7bb1', max_length=48, null=True)),
                ('gender', models.BooleanField(default=0, help_text='0=\u7537\uff0c1=\u5973')),
                ('remark', models.TextField(blank=True, help_text='\u7b80\u4ecb', null=True)),
                ('registersource', models.SmallIntegerField(choices=[(1, 'pc'), (2, 'ios'), (3, 'android'), (4, 'mobileweb')], default=1, help_text='\u6ce8\u518c\u6765\u6e90')),
                ('lastmodifytime', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False, help_text='\u767b\u5f55admin')),
                ('is_active', models.BooleanField(default=True, help_text='\u662f\u5426\u6d3b\u8dc3')),
                ('is_deleted', models.BooleanField(default=False, help_text='\u662f\u5426\u5df2\u88ab\u5220\u9664')),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('createuser', models.ForeignKey(blank=True, help_text='\u521b\u5efa\u8005', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_users', related_query_name='user_createuser', to=settings.AUTH_USER_MODEL)),
                ('deleteduser', models.ForeignKey(blank=True, help_text='\u5220\u9664\u8005', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_users', related_query_name='user_deleteduser', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('lastmodifyuser', models.ForeignKey(blank=True, help_text='\u4fee\u6539\u8005', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_users', related_query_name='user_modifyuser', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, help_text='\u6240\u5c5e\u673a\u6784', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_users', to='org.organization')),
                ('school', models.ForeignKey(blank=True, help_text='\u9662\u6821', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_users', to='sourcetype.School')),
                ('specialty', models.ForeignKey(blank=True, help_text='\u4e13\u4e1a', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profession_users', to='sourcetype.Specialty')),
            ],
            options={
                'db_table': 'user',
                'permissions': (('as_investoruser', '\u6295\u8d44\u4eba'), ('as_traderuser', '\u4ea4\u6613\u5e08'), ('as_supporteruser', '\u9879\u76ee\u65b9'), ('as_adminuser', '\u666e\u901a\u7ba1\u7406\u5458'), ('trader_adduser', '\u4ea4\u6613\u5e08\u65b0\u589e'), ('admin_adduser', '\u7ba1\u7406\u5458\u65b0\u589e'), ('trader_changeuser', '\u4ea4\u6613\u5e08\u7f16\u8f91'), ('admin_changeuser', '\u7ba1\u7406\u5458\u7f16\u8f91')),
            },
        ),
        migrations.CreateModel(
            name='MobileAuthCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(help_text='\u624b\u673a\u53f7', max_length=32)),
                ('token', models.CharField(help_text='\u9a8c\u8bc1\u7801token', max_length=32)),
                ('code', models.CharField(help_text='\u9a8c\u8bc1\u7801', max_length=32)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mobileAuthCode',
            },
        ),
        migrations.CreateModel(
            name='MyToken',
            fields=[
                ('key', models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u88ab\u5220\u9664')),
                ('clienttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sourcetype.ClientType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to=settings.AUTH_USER_MODEL, verbose_name='MyUser')),
            ],
            options={
                'db_table': 'user_token',
            },
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationtype', models.BooleanField(default=False, help_text='\u5f3a\u5173\u7cfbTrue\uff0c\u5f31\u5173\u7cfbFalse')),
                ('score', models.SmallIntegerField(blank=True, default=0, help_text='\u4ea4\u6613\u5e08\u8bc4\u5206')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(blank=True, null=True)),
                ('createuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_relations', to=settings.AUTH_USER_MODEL)),
                ('deleteduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_relations', to=settings.AUTH_USER_MODEL)),
                ('investoruser', models.ForeignKey(help_text='\u4f5c\u4e3a\u6295\u8d44\u4eba', on_delete=django.db.models.deletion.CASCADE, related_name='investor_relations', to=settings.AUTH_USER_MODEL)),
                ('lastmodifyuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodify_relations', to=settings.AUTH_USER_MODEL)),
                ('traderuser', models.ForeignKey(help_text='\u4f5c\u4e3a\u4ea4\u6613\u5e08', on_delete=django.db.models.deletion.CASCADE, related_name='trader_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_relation',
                'permissions': (('admin_adduserrelation', '\u7ba1\u7406\u5458\u5efa\u7acb\u7528\u6237\u8054\u7cfb'), ('admin_changeuserrelation', '\u7ba1\u7406\u5458\u4fee\u6539\u7528\u6237\u8054\u7cfb'), ('admin_deleteuserrelation', '\u7ba1\u7406\u5458\u5220\u9664\u7528\u6237\u8054\u7cfb')),
            },
        ),
        migrations.CreateModel(
            name='userTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(auto_created=True)),
                ('isdeleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_usertags', to=settings.AUTH_USER_MODEL)),
                ('deleteduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_tags', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tags', to='sourcetype.Tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tags',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='tags',
            field=models.ManyToManyField(blank=True, through='usersys.userTags', to='sourcetype.Tag'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_users', related_query_name='user_title', to='sourcetype.TitleType'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='userstatu',
            field=models.ForeignKey(blank=True, help_text='\u4f5c\u8005', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.AuditStatus'),
        ),
    ]
