# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='usercode',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
