# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0002_auto_20170412_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='remark',
            field=models.TextField(blank=True, help_text='\u5907\u6ce8', null=True),
        ),
    ]
