# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0003_auto_20170413_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertags',
            old_name='isdeleted',
            new_name='is_deleted',
        ),
    ]
