# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-20 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0010_auto_20170420_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertags',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='sourcetype.Tag'),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
