# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-20 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0013_auto_20170420_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='name',
            new_name='nameC',
        ),
    ]
