# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0015_auto_20170425_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileAuthCode',
        ),
    ]
