# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0016_delete_mobileauthcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cardKey',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lastmodifytime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='photoKey',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
