# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-05 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0017_auto_20170502_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriendship',
            fields=[
                ('createdtime', models.DateTimeField(auto_created=True, blank=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isaccept', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_userfriends', to=settings.AUTH_USER_MODEL)),
                ('deleteduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_userfriends', to=settings.AUTH_USER_MODEL)),
                ('friend', models.ForeignKey(help_text='\u7528\u6237\u7684\u597d\u53cb', on_delete=django.db.models.deletion.CASCADE, related_name='friend_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='\u7528\u6237', on_delete=django.db.models.deletion.CASCADE, related_name='user_friends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='usertags',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_usertags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='deleteduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_usertags', to=settings.AUTH_USER_MODEL),
        ),
    ]
