# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-12 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0024_auto_20170511_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='userstatus',
            field=models.ForeignKey(blank=True, default=1, help_text='\u5ba1\u6838\u72b6\u6001', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.AuditStatus'),
        ),
    ]
