# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-12 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0026_auto_20170512_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='datasource',
            field=models.ForeignKey(blank=True, help_text='\u6570\u636e\u6e90', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
    ]
