# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-16 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0028_auto_20170515_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytoken',
            name='clienttype',
            field=models.ForeignKey(help_text='\u767b\u5f55\u7c7b\u578b', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.ClientType'),
        ),
    ]
