# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-17 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0029_auto_20170516_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_users', through='usersys.userTags', to='sourcetype.Tag'),
        ),
    ]
