# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0031_auto_20170519_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='nameC',
            new_name='usernameC',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='nameE',
            new_name='usernameE',
        ),
    ]
