# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0032_auto_20170523_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytoken',
            name='clienttype',
            field=utils.customClass.MyForeignKey(help_text='\u767b\u5f55\u7c7b\u578b', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.ClientType'),
        ),
        migrations.AlterField(
            model_name='mytoken',
            name='user',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to=settings.AUTH_USER_MODEL, verbose_name='MyUser'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.Country'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u521b\u5efa\u8005', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_users', related_query_name='user_createuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='datasource',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u6570\u636e\u6e90', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u5220\u9664\u8005', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_users', related_query_name='user_deleteduser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u4fee\u6539\u8005', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_users', related_query_name='user_modifyuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='org',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u6240\u5c5e\u673a\u6784', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_users', to='org.organization'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='school',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u9662\u6821', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_users', to='sourcetype.School'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='specialty',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u4e13\u4e1a', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profession_users', to='sourcetype.Specialty'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='title',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_users', related_query_name='user_title', to='sourcetype.TitleType'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='userstatus',
            field=utils.customClass.MyForeignKey(blank=True, default=1, help_text='\u5ba1\u6838\u72b6\u6001', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.AuditStatus'),
        ),
        migrations.AlterField(
            model_name='userfriendship',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_userfriends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfriendship',
            name='datasource',
            field=utils.customClass.MyForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='userfriendship',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_userfriends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfriendship',
            name='friend',
            field=utils.customClass.MyForeignKey(help_text='\u63a5\u6536\u4eba', on_delete=django.db.models.deletion.CASCADE, related_name='friend_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfriendship',
            name='user',
            field=utils.customClass.MyForeignKey(help_text='\u53d1\u8d77\u4eba', on_delete=django.db.models.deletion.CASCADE, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='datasource',
            field=utils.customClass.MyForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='investoruser',
            field=utils.customClass.MyForeignKey(help_text='\u4f5c\u4e3a\u6295\u8d44\u4eba', on_delete=django.db.models.deletion.CASCADE, related_name='investor_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodify_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='traderuser',
            field=utils.customClass.MyForeignKey(help_text='\u4f5c\u4e3a\u4ea4\u6613\u5e08', on_delete=django.db.models.deletion.CASCADE, related_name='trader_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_usertags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_usertags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='tag',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_usertags', to='sourcetype.Tag'),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='user',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_usertags', to=settings.AUTH_USER_MODEL),
        ),
    ]
