# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0035_auto_20170614_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
