# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-21 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0038_auto_20170720_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='userlevel',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='\u7528\u6237\u670d\u52a1\u7ea7\u522b'),
        ),
    ]
