# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0042_auto_20170727_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cardBucket',
            field=models.CharField(blank=True, default='image', max_length=32),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='photoBucket',
            field=models.CharField(blank=True, default='image', max_length=32),
        ),
    ]
