# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-31 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0029_organization_orglevel'),
        ('sourcetype', '0020_auto_20170725_1616'),
        ('usersys', '0044_auto_20170731_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnreachUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createuser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_unreachUsers', to=settings.AUTH_USER_MODEL)),
                ('deleteduser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_unreachUsers', to=settings.AUTH_USER_MODEL)),
                ('org', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_unreachuser', to='org.organization')),
                ('title', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.TitleType')),
            ],
            options={
                'db_table': 'unreachuser',
            },
        ),
    ]
