# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-31 17:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0020_auto_20170725_1616'),
        ('usersys', '0045_unreachuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreachuser',
            name='datasource',
            field=utils.customClass.MyForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
    ]
