# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-01 10:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0020_auto_20170725_1616'),
        ('usersys', '0046_unreachuser_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='orgarea',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u673a\u6784\u5730\u533a', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.OrgArea'),
        ),
    ]
