# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-09 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0048_auto_20170803_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='department',
            field=models.CharField(blank=True, help_text='\u90e8\u95e8', max_length=64, null=True),
        ),
    ]
