# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-11 10:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0049_myuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriendship',
            name='datasource',
            field=utils.customClass.MyForeignKey(blank=True, default=1, help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='datasource',
            field=utils.customClass.MyForeignKey(blank=True, default=1, help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
    ]
