# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-21 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0025_auto_20170808_1121'),
        ('usersys', '0050_auto_20170811_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRemarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastmodifytime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_remarks',
            },
        ),
        migrations.AlterField(
            model_name='myuser',
            name='remark',
            field=models.TextField(blank=True, help_text='\u7528\u6237\u4e2a\u4eba\u5907\u6ce8', null=True),
        ),
        migrations.AddField(
            model_name='userremarks',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_userremarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userremarks',
            name='datasource',
            field=utils.customClass.MyForeignKey(default=1, help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AddField(
            model_name='userremarks',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_userremarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userremarks',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodify_userremarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userremarks',
            name='user',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_remarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
