# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-31 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0052_auto_20170828_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='registersource',
            field=models.SmallIntegerField(choices=[(1, 'pc'), (2, 'ios'), (3, 'android'), (4, 'mobileweb'), (5, 'unknown')], default=1, help_text='\u6ce8\u518c\u6765\u6e90'),
        ),
        migrations.AlterField(
            model_name='userremarks',
            name='createdtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
