# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timeline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isClose', models.BooleanField(default=False)),
                ('closeDate', models.DateTimeField(blank=True, null=True)),
                ('contractedServiceTime', models.DateTimeField(blank=True, null=True)),
                ('turnoverTime', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'timeline',
            },
        ),
        migrations.CreateModel(
            name='timelineremark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'timelineremarks',
            },
        ),
        migrations.CreateModel(
            name='timelineTransationStatu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=False)),
                ('alertCycle', models.SmallIntegerField(blank=True, null=True)),
                ('inDate', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'timelineTransationStatus',
            },
        ),
    ]
