# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 06:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0001_initial'),
        ('proj', '0002_auto_20170412_1437'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sourcetype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinetransationstatu',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_timelinestatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelinetransationstatu',
            name='deleteduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_timelinestatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelinetransationstatu',
            name='lastmodifyuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_timelinestatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelinetransationstatu',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_transationStatus', to='timeline.timeline'),
        ),
        migrations.AddField(
            model_name='timelinetransationstatu',
            name='transationStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sourcetype.TransactionStatus'),
        ),
        migrations.AddField(
            model_name='timelineremark',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_timelineremarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelineremark',
            name='deleteduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_timelineremarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelineremark',
            name='lastmodifyuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_timelineremarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelineremark',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_remarks', to='timeline.timeline'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeline',
            name='deleteduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeline',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeline',
            name='lastmodifyuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeline',
            name='proj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_timelines', to='proj.project'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporter_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeline',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trader_timelines', to=settings.AUTH_USER_MODEL),
        ),
    ]
