# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-25 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0003_orgarea_namee'),
        ('timeline', '0002_auto_20170412_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'permissions': (('admin_getline', '\u7ba1\u7406\u5458\u67e5\u770b\u65f6\u95f4\u8f74'), ('admin_changeline', '\u7ba1\u7406\u5458\u4fee\u6539\u65f6\u95f4\u8f74'), ('admin_deleteline', '\u7ba1\u7406\u5458\u5220\u9664\u65f6\u95f4\u8f74'), ('admin_addline', '\u7ba1\u7406\u5458\u6dfb\u52a0\u65f6\u95f4\u8f74'), ('user_addline', '\u7528\u6237\u6dfb\u52a0\u65f6\u95f4\u8f74'), ('user_changeline', '\u7528\u6237\u4fee\u6539\u65f6\u95f4\u8f74(obj\u7ea7\u522b)'), ('user_deleteline', '\u7528\u6237\u5220\u9664\u65f6\u95f4\u8f74(obj\u7ea7\u522b)'))},
        ),
        migrations.AddField(
            model_name='timeline',
            name='datasource',
            field=models.ForeignKey(default=1, help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AddField(
            model_name='timelineremark',
            name='datasource',
            field=models.ForeignKey(default=1, help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='timelinetransationstatu',
            name='alertCycle',
            field=models.SmallIntegerField(blank=True, default=7),
        ),
        migrations.AlterField(
            model_name='timelinetransationstatu',
            name='transationStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.TransactionStatus'),
        ),
    ]
