# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20170425_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineremark',
            options={'permissions': (('admin_addlineremark', '\u7ba1\u7406\u5458\u6dfb\u52a0\u65f6\u95f4\u8f74\u5907\u6ce8'), ('admin_getlineremark', '\u7ba1\u7406\u5458\u67e5\u770b\u65f6\u95f4\u8f74\u5907\u6ce8'), ('admin_changelineremark', '\u7ba1\u7406\u5458\u4fee\u6539\u65f6\u95f4\u8f74\u5907\u6ce8'), ('admin_deletelineremark', '\u7ba1\u7406\u5458\u5220\u9664\u65f6\u95f4\u8f74\u5907\u6ce8'), ('user_addlineremark', '\u7528\u6237\u6dfb\u52a0\u65f6\u95f4\u8f74\u5907\u6ce8\uff08obj\u7ea7\u522b/\u76f8\u5bf9timeline)'), ('user_getlineremark', '\u7528\u6237\u67e5\u770b\u65f6\u95f4\u8f74\u5907\u6ce8\uff08obj\u7ea7\u522b)'), ('user_changelineremark', '\u7528\u6237\u4fee\u6539\u65f6\u95f4\u8f74\u5907\u6ce8\uff08obj\u7ea7\u522b)'), ('user_deletelineremark', '\u7528\u6237\u5220\u9664\u65f6\u95f4\u8f74\u5907\u6ce8\uff08obj\u7ea7\u522b)'))},
        ),
    ]
