# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_auto_20170502_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='lastmodifytime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
