# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-12 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0006_auto_20170502_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='supporter',
        ),
        migrations.AddField(
            model_name='timeline',
            name='supportor',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='supportor_timelines', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
