# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_auto_20170512_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='datasource',
            field=utils.customClass.MyForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='investor',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='proj',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_timelines', to='proj.project'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='supportor',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportor_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='trader',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelineremark',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_timelineremarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelineremark',
            name='datasource',
            field=utils.customClass.MyForeignKey(default=1, help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='timelineremark',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_timelineremarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelineremark',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_timelineremarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelineremark',
            name='timeline',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_remarks', to='timeline.timeline'),
        ),
        migrations.AlterField(
            model_name='timelinetransationstatu',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_timelinestatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelinetransationstatu',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_timelinestatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelinetransationstatu',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_timelinestatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelinetransationstatu',
            name='timeline',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_transationStatus', to='timeline.timeline'),
        ),
        migrations.AlterField(
            model_name='timelinetransationstatu',
            name='transationStatus',
            field=utils.customClass.MyForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.TransactionStatus'),
        ),
    ]
