# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-14 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_auto_20170605_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'permissions': (('admin_getline', '\u7ba1\u7406\u5458\u67e5\u770b\u65f6\u95f4\u8f74'), ('admin_changeline', '\u7ba1\u7406\u5458\u4fee\u6539\u65f6\u95f4\u8f74'), ('admin_deleteline', '\u7ba1\u7406\u5458\u5220\u9664\u65f6\u95f4\u8f74'), ('admin_addline', '\u7ba1\u7406\u5458\u6dfb\u52a0\u65f6\u95f4\u8f74'), ('user_addline', '\u7528\u6237\u6dfb\u52a0\u65f6\u95f4\u8f74'), ('user_getline', '\u7528\u6237\u67e5\u770b\u65f6\u95f4\u8f74(obj\u7ea7\u522b)'), ('user_changeline', '\u7528\u6237\u4fee\u6539\u65f6\u95f4\u8f74(obj\u7ea7\u522b)'), ('user_deleteline', '\u7528\u6237\u5220\u9664\u65f6\u95f4\u8f74(obj\u7ea7\u522b)'))},
        ),
    ]
