# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-19 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_auto_20170713_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='supportor',
        ),
    ]
