# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_remove_timeline_supportor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinetransationstatu',
            name='alertCycle',
            field=models.SmallIntegerField(blank=True, default=7, help_text='\u63d0\u9192\u5468\u671f'),
        ),
        migrations.AlterField(
            model_name='timelinetransationstatu',
            name='inDate',
            field=models.DateTimeField(blank=True, help_text='\u63d0\u9192\u5230\u671f\u65f6\u95f4', null=True),
        ),
    ]
