# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-25 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0012_auto_20170725_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='investor',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='proj',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_timelines', to='proj.project'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='trader',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trader_timelines', to=settings.AUTH_USER_MODEL),
        ),
    ]
