# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-06 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0013_auto_20170725_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='createdtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineremark',
            name='createdtime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelinetransationstatu',
            name='createdtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
