# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-25 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import proj.models
import usersys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emailgroupsendlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendtime', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('proj', models.IntegerField(blank=True, help_text='\u9879\u76ee', null=True, verbose_name=proj.models.project)),
                ('projtitle', models.TextField(blank=True, null=True)),
                ('user', models.IntegerField(blank=True, help_text='\u7528\u6237', null=True, verbose_name=usersys.models.MyUser)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('userEmail', models.CharField(blank=True, max_length=64, null=True)),
                ('isRead', models.BooleanField(default=False, help_text='\u7528\u6237\u662f\u5426\u5df2\u8bfb')),
                ('readtime', models.DateTimeField(blank=True, null=True)),
                ('isSend', models.BooleanField(default=False, help_text='\u662f\u5426\u53d1\u9001\u90ae\u4ef6\u6210\u529f')),
                ('errmsg', models.TextField(blank=True, help_text='\u53d1\u9001\u5931\u8d25\u539f\u56e0', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('datasource', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
