# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-25 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailgroupsendlist',
            name='proj',
            field=models.IntegerField(blank=True, help_text='\u9879\u76ee', null=True),
        ),
        migrations.AlterField(
            model_name='emailgroupsendlist',
            name='user',
            field=models.IntegerField(blank=True, help_text='\u7528\u6237', null=True),
        ),
    ]
