# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-09 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAuthCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileareacode', models.CharField(blank=True, default=86, max_length=8)),
                ('mobile', models.CharField(help_text='\u624b\u673a\u53f7', max_length=32)),
                ('token', models.CharField(help_text='\u9a8c\u8bc1\u7801token', max_length=32)),
                ('code', models.CharField(help_text='\u9a8c\u8bc1\u7801', max_length=32)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mobileAuthCode',
            },
        ),
    ]
