# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-19 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0002_mobileauthcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileauthcode',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobileauthcode',
            name='mobileareacode',
            field=models.CharField(blank=True, default=86, max_length=8),
        ),
    ]
