# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('decisionCycle', models.SmallIntegerField(default=180)),
                ('decisionMakingProcess', models.TextField(blank=True, null=True)),
                ('nameC', models.CharField(max_length=128, unique=True)),
                ('nameE', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('orgcode', models.CharField(max_length=128, unique=True)),
                ('transactionAmountF', models.BigIntegerField(blank=True, null=True)),
                ('transactionAmountT', models.BigIntegerField(blank=True, null=True)),
                ('weChat', models.CharField(blank=True, max_length=32, null=True)),
                ('fundSize', models.BigIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('typicalCase', models.TextField(blank=True, null=True)),
                ('fundSize_USD', models.BigIntegerField(blank=True, null=True)),
                ('transactionAmountF_USD', models.BigIntegerField(blank=True, null=True)),
                ('transactionAmountT_USD', models.BigIntegerField(blank=True, null=True)),
                ('partnerOrInvestmentCommiterMember', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('webSite', models.URLField(blank=True, null=True)),
                ('companyEmail', models.EmailField(blank=True, max_length=32, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleteuime', models.DateTimeField(blank=True, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='orgRemarks',
            fields=[
                ('createdtime', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('lastmodifytime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orgremark',
            },
        ),
        migrations.CreateModel(
            name='orgTransactionPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(auto_created=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'org_TransactionPhase',
            },
        ),
    ]
