# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 06:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sourcetype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgtransactionphase',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_orgTransactionPhase', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgtransactionphase',
            name='deleteduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_orgTransactionPhases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgtransactionphase',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_orgTransactionPhases', to='org.organization'),
        ),
        migrations.AddField(
            model_name='orgtransactionphase',
            name='transactionPhase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactionPhase_orgTransactionPhases', to='sourcetype.TransactionPhases'),
        ),
        migrations.AddField(
            model_name='orgremarks',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_orgremarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgremarks',
            name='deleteduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_orgremarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgremarks',
            name='lastmodifyuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_orgremarks', related_query_name='orgremark_modifyuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgremarks',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='auditStatu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.AuditStatus'),
        ),
        migrations.AddField(
            model_name='organization',
            name='auditUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useraudit_org', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_orgs', to='sourcetype.CurrencyType'),
        ),
        migrations.AddField(
            model_name='organization',
            name='deleteuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='lastmodifyuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='orgtransactionphase',
            field=models.ManyToManyField(blank=True, through='org.orgTransactionPhase', to='sourcetype.TransactionPhases'),
        ),
        migrations.AddField(
            model_name='organization',
            name='orgtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.OrgType'),
        ),
    ]
