# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20170412_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('adminadd_org', '\u7ba1\u7406\u5458\u65b0\u589e\u673a\u6784'), ('adminchange_org', '\u7ba1\u7406\u5458\u4fee\u6539\u673a\u6784'), ('admindelete_org', '\u7ba1\u7406\u5458\u5220\u9664\u673a\u6784'), ('get_organization', '\u67e5\u770b\u673a\u6784\u4fe1\u606f'))},
        ),
        migrations.AddField(
            model_name='organization',
            name='investoverseasproject',
            field=models.BooleanField(default=True, help_text='\u662f\u5426\u6295\u6d77\u5916\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='nameC',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='nameE',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='orgcode',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
