# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0001_initial'),
        ('org', '0003_auto_20170414_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='\u673a\u6784\u884c\u4e1a', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.Industry'),
        ),
        migrations.AddField(
            model_name='organization',
            name='mobileAreaCode',
            field=models.CharField(blank=True, default='86', help_text='\u7535\u8bdd\u533a\u53f7', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='auditUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useraudit_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='deleteuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='lastmodifyuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodify_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orgtransactionphase',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactionPhase_orgs', to='org.organization'),
        ),
        migrations.AlterField(
            model_name='orgtransactionphase',
            name='transactionPhase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_orgTransactionPhases', to='sourcetype.TransactionPhases'),
        ),
    ]
