# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_auto_20170418_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('admin_addorg', '\u7ba1\u7406\u5458\u65b0\u589e\u673a\u6784'), ('admin_changeorg', '\u7ba1\u7406\u5458\u4fee\u6539\u673a\u6784'), ('admin_deleteorg', '\u7ba1\u7406\u5458\u5220\u9664\u673a\u6784'), ('admin_getorg', '\u7ba1\u7406\u5458\u67e5\u770b\u673a\u6784\u4fe1\u606f'), ('user_addorg', '\u7528\u6237\u65b0\u589e\u673a\u6784'), ('user_changeorg', '\u7528\u6237\u4fee\u6539\u673a\u6784(obj\u7ea7\u522b\u6743\u9650)'), ('user_deleteorg', '\u7528\u6237\u5220\u9664\u673a\u6784(obj\u7ea7\u522b\u6743\u9650)'), ('user_getorg', '\u7528\u6237\u67e5\u770b\u673a\u6784'))},
        ),
        migrations.AlterModelOptions(
            name='orgremarks',
            options={'permissions': (('admin_getremark', '\u7ba1\u7406\u5458\u67e5\u770b\u673a\u6784\u5907\u6ce8'), ('admin_changeremark', '\u7ba1\u7406\u5458\u4fee\u6539\u673a\u6784\u5907\u6ce8'), ('admin_addremark', '\u7ba1\u7406\u5458\u589e\u52a0\u673a\u6784\u5907\u6ce8'), ('admin_deleteremark', '\u7ba1\u7406\u5458\u5220\u9664\u673a\u6784\u5907\u6ce8'), ('user_getremark', '\u7528\u6237\u67e5\u770b\u673a\u6784\u5907\u6ce8\uff08obj\u7ea7\u522b\uff09'), ('user_changeremark', '\u7528\u6237\u4fee\u6539\u673a\u6784\u5907\u6ce8\uff08obj\u7ea7\u522b\uff09'), ('user_addremark', '\u7528\u6237\u589e\u52a0\u673a\u6784\u5907\u6ce8'), ('user_deleteremark', '\u7528\u6237\u5220\u9664\u673a\u6784\u5907\u6ce8\uff08obj\u7ea7\u522b\uff09'))},
        ),
        migrations.AlterField(
            model_name='organization',
            name='auditStatu',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.AuditStatus'),
        ),
    ]
