# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-25 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_auto_20170420_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgremarks',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_remarks', to='org.organization'),
        ),
        migrations.AlterField(
            model_name='orgtransactionphase',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_orgTransactionPhases', to='org.organization'),
        ),
        migrations.AlterField(
            model_name='orgtransactionphase',
            name='transactionPhase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactionPhase_orgs', to='sourcetype.TransactionPhases'),
        ),
    ]
