# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_auto_20170425_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgremarks',
            options={'permissions': (('admin_getorgremark', '\u7ba1\u7406\u5458\u67e5\u770b\u673a\u6784\u5907\u6ce8'), ('admin_changeorgremark', '\u7ba1\u7406\u5458\u4fee\u6539\u673a\u6784\u5907\u6ce8'), ('admin_addorgremark', '\u7ba1\u7406\u5458\u589e\u52a0\u673a\u6784\u5907\u6ce8'), ('admin_deleteorgremark', '\u7ba1\u7406\u5458\u5220\u9664\u673a\u6784\u5907\u6ce8'), ('user_getorgremark', '\u7528\u6237\u67e5\u770b\u673a\u6784\u5907\u6ce8\uff08obj\u7ea7\u522b\uff09'), ('user_changeorgremark', '\u7528\u6237\u4fee\u6539\u673a\u6784\u5907\u6ce8\uff08obj\u7ea7\u522b\uff09'), ('user_addorgremark', '\u7528\u6237\u589e\u52a0\u673a\u6784\u5907\u6ce8'), ('user_deleteorgremark', '\u7528\u6237\u5220\u9664\u673a\u6784\u5907\u6ce8\uff08obj\u7ea7\u522b\uff09'))},
        ),
    ]
