# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-28 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_auto_20170427_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgremarks',
            old_name='createdtime',
            new_name='createtime',
        ),
    ]
