# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-12 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0006_auto_20170510_1045'),
        ('org', '0012_auto_20170508_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='auditStatu',
        ),
        migrations.AddField(
            model_name='organization',
            name='orgStatus',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.AuditStatus'),
        ),
    ]
