# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0014_auto_20170512_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='lastmodifytime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgremarks',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgremarks',
            name='lastmodifytime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgtransactionphase',
            name='createdtime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
