# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-22 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0017_auto_20170519_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='webSite',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
