# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-27 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0021_auto_20170525_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='currency',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.CurrencyType'),
        ),
    ]
