# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-27 13:35
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import org.models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0022_auto_20170527_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='currency',
            field=org.models.MyForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.CurrencyType'),
        ),
    ]
