# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0025_auto_20170527_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='auditUser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useraudit_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='datasource',
            field=utils.customClass.MyForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='deleteuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u673a\u6784\u884c\u4e1a', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.Industry'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodify_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='orgstatus',
            field=utils.customClass.MyForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.AuditStatus'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='orgtype',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.OrgType'),
        ),
        migrations.AlterField(
            model_name='orgremarks',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_orgremarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orgremarks',
            name='datasource',
            field=utils.customClass.MyForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='orgremarks',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_orgremarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orgremarks',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_orgremarks', related_query_name='orgremark_modifyuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orgremarks',
            name='org',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_remarks', to='org.organization'),
        ),
        migrations.AlterField(
            model_name='orgtransactionphase',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_orgTransactionPhase', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orgtransactionphase',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_orgTransactionPhases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orgtransactionphase',
            name='org',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_orgTransactionPhases', to='org.organization'),
        ),
        migrations.AlterField(
            model_name='orgtransactionphase',
            name='transactionPhase',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactionPhase_orgs', to='sourcetype.TransactionPhases'),
        ),
    ]
