# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-19 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0027_auto_20170608_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='createtime',
            new_name='createdtime',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='deletetime',
            new_name='deletedtime',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='deleteuser',
            new_name='deleteduser',
        ),
        migrations.RenameField(
            model_name='orgremarks',
            old_name='createtime',
            new_name='createdtime',
        ),
    ]
