# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0030_auto_20170802_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('admin_addorg', '\u7ba1\u7406\u5458\u65b0\u589e\u673a\u6784'), ('admin_changeorg', '\u7ba1\u7406\u5458\u4fee\u6539\u673a\u6784'), ('admin_deleteorg', '\u7ba1\u7406\u5458\u5220\u9664\u673a\u6784'), ('admin_getorg', '\u7ba1\u7406\u5458\u67e5\u770b\u673a\u6784\u4fe1\u606f'), ('user_addorg', '\u7528\u6237\u65b0\u589e\u673a\u6784'), ('user_changeorg', '\u7528\u6237\u4fee\u6539\u673a\u6784(obj\u7ea7\u522b\u6743\u9650)'), ('user_deleteorg', '\u7528\u6237\u5220\u9664\u673a\u6784(obj\u7ea7\u522b\u6743\u9650)'), ('user_getorg', '\u7528\u6237\u67e5\u770b\u673a\u6784'))},
        ),
    ]
