# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-28 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0031_auto_20170804_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
