# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-29 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0032_auto_20170828_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='companyEmail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='webSite',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
