# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-07 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0026_orgattribute'),
        ('org', '0033_auto_20170829_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='orgcode',
        ),
        migrations.AddField(
            model_name='organization',
            name='businessscope',
            field=models.TextField(blank=True, help_text='\u7ecf\u8425\u8303\u56f4', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='launchdate',
            field=models.DateTimeField(blank=True, help_text='\u4e0a\u5e02\u65e5\u671f', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='mainproductname',
            field=models.TextField(blank=True, help_text='\u4e3b\u8425\u4ea7\u54c1\u540d\u79f0', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='mainproducttype',
            field=models.TextField(blank=True, help_text='\u4e3b\u8425\u4ea7\u54c1\u7c7b\u522b', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='officeaddress',
            field=models.TextField(blank=True, help_text='\u529e\u516c\u5730\u5740', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='orgattribute',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u673a\u6784\u5c5e\u6027\uff08\u56fd\u6709\u3001\u6c11\u8425\u3001\u5730\u65b9\u3001\u4e2d\u592e\uff09', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.OrgAttribute'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stockcode',
            field=models.CharField(blank=True, help_text='\u8bc1\u5238\u4ee3\u7801', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='stockshortname',
            field=models.CharField(blank=True, help_text='\u8bc1\u5238\u7b80\u79f0', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='totalemployees',
            field=models.IntegerField(blank=True, help_text='\u5458\u5de5\u603b\u6570', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='orgtype',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u673a\u6784\u7c7b\u578b\uff08\u57fa\u91d1\u3001\u8bc1\u5238\u3001\u4e0a\u5e02\u516c\u53f8\uff09', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.OrgType'),
        ),
    ]
