# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-08 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0034_auto_20170907_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='officeaddress',
        ),
    ]
