# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-11 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0035_remove_organization_officeaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='launchdate',
            new_name='IPOdate',
        ),
    ]
