# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-11 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0036_auto_20170911_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='marketvalue',
            field=models.BigIntegerField(blank=True, help_text='\u603b\u5e02\u503c', null=True),
        ),
    ]
