# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcetype', '0003_orgarea_namee'),
        ('proj', '0010_auto_20170428_1522'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dataroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isPublic', models.BooleanField(default=False, help_text='\u662f\u5426\u662f\u516c\u5171\u6587\u4ef6\u5939')),
                ('isClose', models.BooleanField(default=False, help_text='\u662f\u5426\u5173\u95ed')),
                ('closeDate', models.DateTimeField(blank=True, help_text='\u5173\u95ed\u65e5\u671f', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(blank=True, null=True)),
                ('createuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_datarooms', to=settings.AUTH_USER_MODEL)),
                ('datasource', models.ForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource')),
                ('deleteduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_datarooms', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(blank=True, help_text='dataroom\u5173\u8054\u7684\u6295\u8d44\u4eba', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_datarooms', to=settings.AUTH_USER_MODEL)),
                ('lastmodifyuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodify_datarooms', to=settings.AUTH_USER_MODEL)),
                ('proj', models.ForeignKey(help_text='dataroom\u5173\u8054\u9879\u76ee', on_delete=django.db.models.deletion.CASCADE, related_name='proj_datarooms', to='proj.project')),
                ('supportor', models.ForeignKey(blank=True, help_text='dataroom\u5173\u8054\u7684\u9879\u76ee\u65b9', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportor_datarooms', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(blank=True, help_text='dataroom\u5173\u8054\u7684\u4ea4\u6613\u5e08', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trader_datarooms', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='dataroom\u7684\u7528\u6237', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_datarooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dataroom',
                'permissions': (('admin_getdataroom', '\u7ba1\u7406\u5458\u67e5\u770bdataroom'), ('admin_changedataroom', '\u7ba1\u7406\u5458\u4fee\u6539dataroom'), ('admin_deletedataroom', '\u7ba1\u7406\u5458\u5220\u9664dataroom'), ('admin_adddataroom', '\u7ba1\u7406\u5458\u6dfb\u52a0dataroom')),
            },
        ),
        migrations.CreateModel(
            name='dataroomdirectory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderNO', models.SmallIntegerField(help_text='\u76ee\u5f55\u6216\u6587\u4ef6\u5728\u6240\u5c5e\u76ee\u5f55\u4e0b\u7684\u6392\u5e8f\u4f4d\u7f6e')),
                ('isShadow', models.BooleanField(default=False)),
                ('size', models.IntegerField(blank=True, help_text='\u6587\u4ef6\u5927\u5c0f', null=True)),
                ('filename', models.CharField(blank=True, help_text='\u6587\u4ef6\u540d', max_length=128, null=True)),
                ('key', models.CharField(blank=True, help_text='\u6587\u4ef6\u8def\u5f84', max_length=16, null=True)),
                ('bucket', models.CharField(blank=True, help_text='\u6587\u4ef6\u6240\u5728\u7a7a\u95f4', max_length=128, null=True)),
                ('isRead', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(blank=True, null=True)),
                ('createuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_dataroomdirectories', to=settings.AUTH_USER_MODEL)),
                ('dataroom', models.ForeignKey(help_text='\u76ee\u5f55\u6216\u6587\u4ef6\u6240\u5c5edataroom', on_delete=django.db.models.deletion.CASCADE, related_name='dataroom_directories', to='dataroom.dataroom')),
                ('datasource', models.ForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource')),
                ('deleteduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_dataroomdirectories', to=settings.AUTH_USER_MODEL)),
                ('lastmodifyuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodify_dataroomdirectories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(help_text='\u76ee\u5f55\u6216\u6587\u4ef6\u6240\u5c5e\u76ee\u5f55id', on_delete=django.db.models.deletion.CASCADE, related_name='directory_directories', to='dataroom.dataroomdirectory')),
                ('shadowdirectory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shadowdirectory_directory', to='dataroom.dataroomdirectory')),
            ],
            options={
                'db_table': 'dataroomdirectory',
                'permissions': (),
            },
        ),
    ]
