# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0003_orgarea_namee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataroomdirectoryorfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderNO', models.PositiveSmallIntegerField(help_text='\u76ee\u5f55\u6216\u6587\u4ef6\u5728\u6240\u5c5e\u76ee\u5f55\u4e0b\u7684\u6392\u5e8f\u4f4d\u7f6e')),
                ('isShadow', models.BooleanField(default=False)),
                ('size', models.IntegerField(blank=True, help_text='\u6587\u4ef6\u5927\u5c0f', null=True)),
                ('name', models.CharField(blank=True, help_text='\u6587\u4ef6\u540d\u6216\u76ee\u5f55\u540d', max_length=128, null=True)),
                ('key', models.CharField(blank=True, help_text='\u6587\u4ef6\u8def\u5f84', max_length=16, null=True)),
                ('bucket', models.CharField(blank=True, help_text='\u6587\u4ef6\u6240\u5728\u7a7a\u95f4', max_length=128, null=True)),
                ('isFile', models.BooleanField(default=False, help_text='true/\u6587\u4ef6\uff0cfalse/\u76ee\u5f55')),
                ('isRead', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(blank=True, null=True)),
                ('createuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_dataroomdirectories', to=settings.AUTH_USER_MODEL)),
                ('dataroom', models.ForeignKey(help_text='\u76ee\u5f55\u6216\u6587\u4ef6\u6240\u5c5edataroom', on_delete=django.db.models.deletion.CASCADE, related_name='dataroom_directories', to='dataroom.dataroom')),
                ('datasource', models.ForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource')),
                ('deleteduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_dataroomdirectories', to=settings.AUTH_USER_MODEL)),
                ('lastmodifyuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodify_dataroomdirectories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(help_text='\u76ee\u5f55\u6216\u6587\u4ef6\u6240\u5c5e\u76ee\u5f55id', on_delete=django.db.models.deletion.CASCADE, related_name='directory_directories', to='dataroom.dataroomdirectoryorfile')),
                ('shadowdirectory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shadowdirectory_directory', to='dataroom.dataroomdirectoryorfile')),
            ],
            options={
                'db_table': 'dataroomdirectoryorfile',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='publicdirectorytemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('orderNO', models.PositiveSmallIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(blank=True, null=True)),
                ('createuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_publicdirectorytemplate', to=settings.AUTH_USER_MODEL)),
                ('datasource', models.ForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource')),
                ('deleteduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_publicdirectorytemplate', to=settings.AUTH_USER_MODEL)),
                ('lastmodifyuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodify_publicdirectorytemplate', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.publicdirectorytemplate')),
            ],
            options={
                'db_table': 'dataroompublicdirectorytemplate',
                'permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='dataroomdirectory',
            name='createuser',
        ),
        migrations.RemoveField(
            model_name='dataroomdirectory',
            name='dataroom',
        ),
        migrations.RemoveField(
            model_name='dataroomdirectory',
            name='datasource',
        ),
        migrations.RemoveField(
            model_name='dataroomdirectory',
            name='deleteduser',
        ),
        migrations.RemoveField(
            model_name='dataroomdirectory',
            name='lastmodifyuser',
        ),
        migrations.RemoveField(
            model_name='dataroomdirectory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='dataroomdirectory',
            name='shadowdirectory',
        ),
        migrations.DeleteModel(
            name='dataroomdirectory',
        ),
    ]
