# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0006_auto_20170524_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroom',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_datarooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataroom',
            name='datasource',
            field=utils.customClass.MyForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='dataroom',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_datarooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataroom',
            name='investor',
            field=utils.customClass.MyForeignKey(blank=True, help_text='dataroom\u5173\u8054\u7684\u6295\u8d44\u4eba', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_datarooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataroom',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodify_datarooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataroom',
            name='proj',
            field=utils.customClass.MyForeignKey(help_text='dataroom\u5173\u8054\u9879\u76ee', on_delete=django.db.models.deletion.CASCADE, related_name='proj_datarooms', to='proj.project'),
        ),
        migrations.AlterField(
            model_name='dataroom',
            name='supportor',
            field=utils.customClass.MyForeignKey(blank=True, help_text='dataroom\u5173\u8054\u7684\u9879\u76ee\u65b9', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportor_datarooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataroom',
            name='trader',
            field=utils.customClass.MyForeignKey(blank=True, help_text='dataroom\u5173\u8054\u7684\u4ea4\u6613\u5e08', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trader_datarooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataroom',
            name='user',
            field=utils.customClass.MyForeignKey(blank=True, help_text='dataroom\u7684\u7528\u6237', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_datarooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataroomdirectoryorfile',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_dataroomdirectories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataroomdirectoryorfile',
            name='dataroom',
            field=utils.customClass.MyForeignKey(help_text='\u76ee\u5f55\u6216\u6587\u4ef6\u6240\u5c5edataroom', on_delete=django.db.models.deletion.CASCADE, related_name='dataroom_directories', to='dataroom.dataroom'),
        ),
        migrations.AlterField(
            model_name='dataroomdirectoryorfile',
            name='datasource',
            field=utils.customClass.MyForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='dataroomdirectoryorfile',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_dataroomdirectories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataroomdirectoryorfile',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodify_dataroomdirectories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataroomdirectoryorfile',
            name='parent',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u76ee\u5f55\u6216\u6587\u4ef6\u6240\u5c5e\u76ee\u5f55id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asparent_directories', to='dataroom.dataroomdirectoryorfile'),
        ),
        migrations.AlterField(
            model_name='dataroomdirectoryorfile',
            name='shadowdirectory',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shadowdirectory_directory', to='dataroom.dataroomdirectoryorfile'),
        ),
        migrations.AlterField(
            model_name='publicdirectorytemplate',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_publicdirectorytemplate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicdirectorytemplate',
            name='datasource',
            field=utils.customClass.MyForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='publicdirectorytemplate',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_publicdirectorytemplate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicdirectorytemplate',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodify_publicdirectorytemplate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicdirectorytemplate',
            name='parent',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataroom.publicdirectorytemplate'),
        ),
    ]
