# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-29 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0009_remove_dataroom_supportor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicdirectorytemplate',
            name='datasource',
        ),
    ]
