# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-13 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0010_remove_publicdirectorytemplate_datasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroom',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataroomdirectoryorfile',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicdirectorytemplate',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
