# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-26 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0011_auto_20170713_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomdirectoryorfile',
            name='orderNO',
            field=models.PositiveSmallIntegerField(blank=True, help_text='\u76ee\u5f55\u6216\u6587\u4ef6\u5728\u6240\u5c5e\u76ee\u5f55\u4e0b\u7684\u6392\u5e8f\u4f4d\u7f6e', default=0),
        ),
    ]
