# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-26 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0012_auto_20170726_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomdirectoryorfile',
            name='key',
            field=models.CharField(blank=True, help_text='\u6587\u4ef6\u8def\u5f84', max_length=128, null=True),
        ),
    ]
