# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-03 17:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0013_auto_20170726_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroom',
            name='user',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u9879\u76ee\u65b9', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_datarooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataroomdirectoryorfile',
            name='bucket',
            field=models.CharField(blank=True, default='file', help_text='\u6587\u4ef6\u6240\u5728\u7a7a\u95f4', max_length=128),
        ),
    ]
