# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(auto_created=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('proj',),
                'db_table': 'project_favorite',
            },
        ),
        migrations.CreateModel(
            name='finance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('netIncome', models.BigIntegerField(blank=True, null=True)),
                ('revenue_USD', models.BigIntegerField(blank=True, null=True)),
                ('netIncome_USD', models.BigIntegerField(blank=True, null=True)),
                ('EBITDA', models.BigIntegerField(blank=True, null=True)),
                ('grossProfit', models.BigIntegerField(blank=True, null=True)),
                ('totalAsset', models.BigIntegerField(blank=True, null=True)),
                ('stockholdersEquity', models.BigIntegerField(blank=True, null=True)),
                ('operationalCashFlow', models.BigIntegerField(blank=True, null=True)),
                ('grossMerchandiseValue', models.BigIntegerField(blank=True, null=True)),
                ('fYear', models.SmallIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletetime', models.DateTimeField(blank=True, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projectFinance',
            },
        ),
        migrations.CreateModel(
            name='format',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('targetMarketC', models.TextField(blank=True, null=True)),
                ('targetMarketE', models.TextField(blank=True, null=True)),
                ('productTechnologyC', models.TextField(blank=True, null=True)),
                ('productTechnologyE', models.TextField(blank=True, null=True)),
                ('businessModelC', models.TextField(blank=True, null=True)),
                ('businessModelE', models.TextField(blank=True, null=True)),
                ('brandSalesChannelC', models.TextField(blank=True, null=True)),
                ('brandSalesChannelE', models.TextField(blank=True, null=True)),
                ('managementC', models.TextField(blank=True, null=True)),
                ('managementE', models.TextField(blank=True, null=True)),
                ('partnersC', models.TextField(blank=True, null=True)),
                ('partnersE', models.TextField(blank=True, null=True)),
                ('useOfProceedC', models.TextField(blank=True, null=True)),
                ('useOfProceedE', models.TextField(blank=True, null=True)),
                ('financingRecordC', models.TextField(blank=True, null=True)),
                ('financingRecordE', models.TextField(blank=True, null=True)),
                ('operatingFiguresC', models.TextField(blank=True, null=True)),
                ('operatingFiguresE', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletetime', models.DateTimeField(blank=True, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projectFormat',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titleC', models.CharField(db_index=True, default='\u6807\u9898', max_length=128)),
                ('titleE', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('c_descriptionC', models.TextField(blank=True, default='\u9879\u76ee\u63cf\u8ff0')),
                ('c_descriptionE', models.TextField(blank=True, default='project description')),
                ('b_introducteC', models.TextField(blank=True, default='\u9879\u76ee\u4ecb\u7ecd')),
                ('b_introducteE', models.TextField(blank=True, default='project introduction')),
                ('isHidden', models.BooleanField(default=False)),
                ('financeAmount', models.BigIntegerField(blank=True, null=True)),
                ('financeAmount_USD', models.BigIntegerField(blank=True, null=True)),
                ('companyValuation', models.BigIntegerField(blank=True, null=True, verbose_name='\u516c\u53f8\u4f30\u503c')),
                ('companyValuation_USD', models.BigIntegerField(blank=True, null=True, verbose_name='\u516c\u53f8\u4f30\u503c')),
                ('companyYear', models.SmallIntegerField(blank=True, null=True, verbose_name='\u516c\u53f8\u5e74\u9650')),
                ('financeIsPublic', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=128, null=True)),
                ('contactPerson', models.CharField(blank=True, max_length=64, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=48, null=True, verbose_name='\u90ae\u7bb1')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletetime', models.DateTimeField(blank=True, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='projectIndustries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(auto_created=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_industries',
            },
        ),
        migrations.CreateModel(
            name='projectTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(auto_created=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_tags',
            },
        ),
        migrations.CreateModel(
            name='projectTransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(auto_created=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_TransactionType',
            },
        ),
    ]
