# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 06:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proj', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sourcetype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttransactiontype',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_projtransactionType', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttransactiontype',
            name='deleteduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_projtransactionTypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttransactiontype',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.project'),
        ),
        migrations.AddField(
            model_name='projecttransactiontype',
            name='transactionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_TransactionTypes', to='sourcetype.TransactionType'),
        ),
        migrations.AddField(
            model_name='projecttags',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_projtag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttags',
            name='deleteduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_projtags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttags',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.project'),
        ),
        migrations.AddField(
            model_name='projecttags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tags', to='sourcetype.Tag'),
        ),
        migrations.AddField(
            model_name='projectindustries',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_projIndustry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectindustries',
            name='deleteduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_projIndustries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectindustries',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_industries', to='sourcetype.Industry'),
        ),
        migrations.AddField(
            model_name='projectindustries',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.Country'),
        ),
        migrations.AddField(
            model_name='project',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcetype.CurrencyType'),
        ),
        migrations.AddField(
            model_name='project',
            name='deleteuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='industries',
            field=models.ManyToManyField(blank=True, through='proj.projectIndustries', to='sourcetype.Industry'),
        ),
        migrations.AddField(
            model_name='project',
            name='lastmodifyuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='projFormat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.format'),
        ),
        migrations.AddField(
            model_name='project',
            name='statu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.ProjectStatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='supportUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usersupport_projs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, through='proj.projectTags', to='sourcetype.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='transactionType',
            field=models.ManyToManyField(blank=True, through='proj.projectTransactionType', to='sourcetype.TransactionType'),
        ),
        migrations.AddField(
            model_name='format',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_formats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='format',
            name='deleteuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_formats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='format',
            name='lastmodifyuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_formats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finance',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_finances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finance',
            name='deleteuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_finances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finance',
            name='lastmodifyuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_finances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finance',
            name='proj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_finances', related_query_name='finance', to='proj.project'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='createuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_favoriteproj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='deleteduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_favoriteproj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favoritetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritetype_proj', to='sourcetype.FavoriteType', verbose_name='\u6536\u85cf\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_favorite', to='proj.project'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
