# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_auto_20170412_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='format',
            old_name='brandSalesChannelC',
            new_name='BusinesspartnersE',
        ),
        migrations.RenameField(
            model_name='format',
            old_name='brandSalesChannelE',
            new_name='brandChannelE',
        ),
        migrations.RenameField(
            model_name='format',
            old_name='financingRecordC',
            new_name='financingHistoryE',
        ),
        migrations.RenameField(
            model_name='format',
            old_name='financingRecordE',
            new_name='managementTeamE',
        ),
        migrations.RenameField(
            model_name='format',
            old_name='managementC',
            new_name='operationalDataE',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='b_introducteC',
            new_name='p_introducteC',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='b_introducteE',
            new_name='p_introducteE',
        ),
        migrations.RemoveField(
            model_name='format',
            name='managementE',
        ),
        migrations.RemoveField(
            model_name='format',
            name='operatingFiguresC',
        ),
        migrations.RemoveField(
            model_name='format',
            name='operatingFiguresE',
        ),
        migrations.RemoveField(
            model_name='format',
            name='partnersC',
        ),
        migrations.RemoveField(
            model_name='format',
            name='partnersE',
        ),
        migrations.AddField(
            model_name='format',
            name='BusinesspartnersC',
            field=models.TextField(blank=True, help_text='\u5546\u4e1a\u4f19\u4f34', null=True),
        ),
        migrations.AddField(
            model_name='format',
            name='brandChannelC',
            field=models.TextField(blank=True, help_text='\u54c1\u724c\u6e20\u9053', null=True),
        ),
        migrations.AddField(
            model_name='format',
            name='financingHistoryC',
            field=models.TextField(blank=True, help_text='\u878d\u8d44\u5386\u53f2', null=True),
        ),
        migrations.AddField(
            model_name='format',
            name='managementTeamC',
            field=models.TextField(blank=True, help_text='\u7ba1\u7406\u56e2\u961f', null=True),
        ),
        migrations.AddField(
            model_name='format',
            name='operationalDataC',
            field=models.TextField(blank=True, help_text='\u7ecf\u8425\u6570\u636e', null=True),
        ),
        migrations.AlterField(
            model_name='format',
            name='businessModelC',
            field=models.TextField(blank=True, help_text='\u5546\u4e1a\u6a21\u5f0f', null=True),
        ),
        migrations.AlterField(
            model_name='format',
            name='productTechnologyC',
            field=models.TextField(blank=True, help_text='\u6838\u5fc3\u6280\u672f', null=True),
        ),
        migrations.AlterField(
            model_name='format',
            name='targetMarketC',
            field=models.TextField(blank=True, help_text='\u76ee\u6807\u5e02\u573a', null=True),
        ),
        migrations.AlterField(
            model_name='format',
            name='useOfProceedC',
            field=models.TextField(blank=True, help_text='\u8d44\u91d1\u7528\u9014', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='c_descriptionC',
            field=models.TextField(blank=True, default='\u516c\u53f8\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='project',
            name='c_descriptionE',
            field=models.TextField(blank=True, default='company description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='companyValuation',
            field=models.BigIntegerField(blank=True, help_text='\u516c\u53f8\u4f30\u503c', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='companyValuation_USD',
            field=models.BigIntegerField(blank=True, help_text='\u516c\u53f8\u4f30\u503c', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='companyYear',
            field=models.SmallIntegerField(blank=True, help_text='\u516c\u53f8\u5e74\u9650', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='contactPerson',
            field=models.CharField(blank=True, help_text='\u8054\u7cfb\u4eba', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='\u8054\u7cfb\u4eba\u90ae\u7bb1', max_length=48, null=True),
        ),
    ]
