# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_auto_20170413_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isoverseasproject',
            field=models.BooleanField(default=True, help_text='\u662f\u5426\u662f\u6d77\u5916\u9879\u76ee'),
        ),
    ]
