# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_project_isoverseasproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('admin_addproj', '\u7ba1\u7406\u5458\u4e0a\u4f20\u9879\u76ee'), ('admin_changeproj', '\u7ba1\u7406\u5458\u4fee\u6539\u9879\u76ee'), ('admin_deleteproj', '\u7ba1\u7406\u5458\u5220\u9664\u9879\u76ee'), ('admin_getproj', '\u7ba1\u7406\u5458\u67e5\u770b\u9879\u76ee'), ('user_addproj', '\u7528\u6237\u4e0a\u4f20\u9879\u76ee'), ('user_changeproj', '\u7528\u6237\u4fee\u6539\u9879\u76ee(obj\u7ea7\u522b)'), ('user_deleteproj', '\u7528\u6237\u5220\u9664\u9879\u76ee(obj\u7ea7\u522b)'), ('user_getproj', '\u7528\u6237\u67e5\u770b\u9879\u76ee(obj\u7ea7\u522b)'))},
        ),
        migrations.AlterField(
            model_name='project',
            name='statu',
            field=models.ForeignKey(default=1, help_text='\u9879\u76ee\u72b6\u6001', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.ProjectStatus'),
        ),
    ]
