# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_auto_20170418_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='createuser',
        ),
        migrations.RemoveField(
            model_name='format',
            name='deleteuser',
        ),
        migrations.RemoveField(
            model_name='format',
            name='lastmodifyuser',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projFormat',
        ),
        migrations.AddField(
            model_name='project',
            name='BusinesspartnersC',
            field=models.TextField(blank=True, help_text='\u5546\u4e1a\u4f19\u4f34', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='BusinesspartnersE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='brandChannelC',
            field=models.TextField(blank=True, help_text='\u54c1\u724c\u6e20\u9053', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='brandChannelE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='businessModelC',
            field=models.TextField(blank=True, help_text='\u5546\u4e1a\u6a21\u5f0f', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='businessModelE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='financingHistoryC',
            field=models.TextField(blank=True, help_text='\u878d\u8d44\u5386\u53f2', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='financingHistoryE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='managementTeamC',
            field=models.TextField(blank=True, help_text='\u7ba1\u7406\u56e2\u961f', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='managementTeamE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='operationalDataC',
            field=models.TextField(blank=True, help_text='\u7ecf\u8425\u6570\u636e', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='operationalDataE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='productTechnologyC',
            field=models.TextField(blank=True, help_text='\u6838\u5fc3\u6280\u672f', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='productTechnologyE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='targetMarketC',
            field=models.TextField(blank=True, help_text='\u76ee\u6807\u5e02\u573a', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='targetMarketE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='useOfProceedC',
            field=models.TextField(blank=True, help_text='\u8d44\u91d1\u7528\u9014', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='useOfProceedE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='format',
        ),
    ]
