# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-25 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0003_orgarea_namee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj', '0006_auto_20170419_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='favoriteProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(auto_created=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_favoriteproj', to=settings.AUTH_USER_MODEL)),
                ('datasource', models.ForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource')),
                ('deleteduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_favoriteproj', to=settings.AUTH_USER_MODEL)),
                ('favoritetype', models.ForeignKey(help_text='\u6536\u85cf\u7c7b\u578b', on_delete=django.db.models.deletion.CASCADE, related_name='favoritetype_proj', to='sourcetype.FavoriteType')),
            ],
            options={
                'ordering': ('proj',),
                'db_table': 'project_favorites',
                'permissions': (('user_addfavorite', '\u7528\u6237\u6dfb\u52a0favorite(obj\u7ea7\u522b\u2014\u2014\u7ed9\u4ea4\u6613\u5e08\u7684)'), ('user_getfavorite', '\u7528\u6237\u67e5\u770bfavorite(obj\u7ea7\u522b\u2014\u2014\u7ed9\u4ea4\u6613\u5e08\u7684)'), ('admin_addfavorite', '\u7ba1\u7406\u5458\u6dfb\u52a0favorite'), ('admin_getfavorite', '\u7ba1\u7406\u5458\u67e5\u770bfavorite'), ('admin_deletefavorite', '\u7ba1\u7406\u5458\u5220\u9664favorite')),
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('admin_addproj', '\u7ba1\u7406\u5458\u4e0a\u4f20\u9879\u76ee'), ('admin_changeproj', '\u7ba1\u7406\u5458\u4fee\u6539\u9879\u76ee'), ('admin_deleteproj', '\u7ba1\u7406\u5458\u5220\u9664\u9879\u76ee'), ('admin_getproj', '\u7ba1\u7406\u5458\u67e5\u770b\u9879\u76ee'), ('user_addproj', '\u7528\u6237\u4e0a\u4f20\u9879\u76ee'), ('user_changeproj', '\u7528\u6237\u4fee\u6539\u9879\u76ee(obj\u7ea7\u522b)'), ('user_deleteproj', '\u7528\u6237\u5220\u9664\u9879\u76ee(obj\u7ea7\u522b)'), ('user_getproj', '\u7528\u6237\u67e5\u770b\u9879\u76ee(obj/class\u7ea7\u522b)'))},
        ),
        migrations.AddField(
            model_name='finance',
            name='datasource',
            field=models.ForeignKey(default=1, help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='datasource',
            field=models.ForeignKey(default=2, help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectindustries',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_projects', to='sourcetype.Industry'),
        ),
        migrations.AlterField(
            model_name='projectindustries',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_industries', to='proj.project'),
        ),
        migrations.AlterField(
            model_name='projecttags',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tags', to='proj.project'),
        ),
        migrations.AlterField(
            model_name='projecttags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_projects', to='sourcetype.Tag'),
        ),
        migrations.AlterField(
            model_name='projecttransactiontype',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_TransactionTypes', to='proj.project'),
        ),
        migrations.AlterField(
            model_name='projecttransactiontype',
            name='transactionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionType_projects', to='sourcetype.TransactionType'),
        ),
        migrations.DeleteModel(
            name='favorite',
        ),
        migrations.AddField(
            model_name='favoriteproject',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_favorite', to='proj.project'),
        ),
        migrations.AddField(
            model_name='favoriteproject',
            name='trader',
            field=models.ForeignKey(blank=True, help_text='\u4ea4\u6613\u5e08id\uff08\u7528\u6237\u611f\u5174\u8da3\u65f6\u8054\u7cfb/\u4ea4\u6613\u5e08\u63a8\u8350\uff09', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trader_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoriteproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
