# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-28 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0009_auto_20170428_1521'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sharetoken',
            table='project_sharetoken',
        ),
    ]
