# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-11 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0010_auto_20170428_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproject',
            name='createdtime',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
