# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-12 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0013_auto_20170511_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='statu',
            new_name='projStatus',
        ),
    ]
