# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-12 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0014_auto_20170512_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projStatus',
            new_name='projstatus',
        ),
    ]
