# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-17 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0015_auto_20170512_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='proj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_finances', to='proj.project'),
        ),
    ]
