# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-24 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0016_auto_20170517_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='titleC',
            new_name='projtitleC',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='titleE',
            new_name='projtitleE',
        ),
    ]
