# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0017_auto_20170524_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproject',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_favoriteproj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteproject',
            name='datasource',
            field=utils.customClass.MyForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='favoriteproject',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_favoriteproj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteproject',
            name='favoritetype',
            field=utils.customClass.MyForeignKey(help_text='\u6536\u85cf\u7c7b\u578b', on_delete=django.db.models.deletion.CASCADE, related_name='favoritetype_proj', to='sourcetype.FavoriteType'),
        ),
        migrations.AlterField(
            model_name='favoriteproject',
            name='proj',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_favorite', to='proj.project'),
        ),
        migrations.AlterField(
            model_name='favoriteproject',
            name='trader',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u4ea4\u6613\u5e08id\uff08\u7528\u6237\u611f\u5174\u8da3\u65f6\u8054\u7cfb/\u4ea4\u6613\u5e08\u63a8\u8350\uff09', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trader_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteproject',
            name='user',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finance',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_finances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finance',
            name='datasource',
            field=utils.customClass.MyForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='deleteuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_finances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finance',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_finances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finance',
            name='proj',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_finances', to='proj.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.Country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=utils.customClass.MyForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcetype.CurrencyType'),
        ),
        migrations.AlterField(
            model_name='project',
            name='datasource',
            field=utils.customClass.MyForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deleteuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='projstatus',
            field=utils.customClass.MyForeignKey(default=1, help_text='\u9879\u76ee\u72b6\u6001', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.ProjectStatus'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supportUser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usersupport_projs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectindustries',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_projIndustry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectindustries',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_projIndustries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectindustries',
            name='industry',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_projects', to='sourcetype.Industry'),
        ),
        migrations.AlterField(
            model_name='projectindustries',
            name='proj',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_industries', to='proj.project'),
        ),
        migrations.AlterField(
            model_name='projecttags',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_projtag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projecttags',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_projtags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projecttags',
            name='proj',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tags', to='proj.project'),
        ),
        migrations.AlterField(
            model_name='projecttags',
            name='tag',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_projects', to='sourcetype.Tag'),
        ),
        migrations.AlterField(
            model_name='projecttransactiontype',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_projtransactionType', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projecttransactiontype',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_projtransactionTypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projecttransactiontype',
            name='proj',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_TransactionTypes', to='proj.project'),
        ),
        migrations.AlterField(
            model_name='projecttransactiontype',
            name='transactionType',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionType_projects', to='sourcetype.TransactionType'),
        ),
        migrations.AlterField(
            model_name='sharetoken',
            name='proj',
            field=utils.customClass.MyForeignKey(help_text='\u9879\u76ee\u7684\u5206\u4eabtoken', on_delete=django.db.models.deletion.CASCADE, related_name='proj_sharetoken', to='proj.project'),
        ),
        migrations.AlterField(
            model_name='sharetoken',
            name='user',
            field=utils.customClass.MyForeignKey(help_text='\u7528\u6237\u7684\u5206\u4eabtoken', on_delete=django.db.models.deletion.CASCADE, related_name='user_sharetoken', to=settings.AUTH_USER_MODEL),
        ),
    ]
