# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-06 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj', '0018_auto_20170605_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=128, null=True)),
                ('filetype', models.CharField(blank=True, max_length=32, null=True)),
                ('bucket', models.CharField(blank=True, default='file', max_length=32)),
                ('key', models.CharField(blank=True, max_length=128, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletetime', models.DateTimeField(blank=True, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(auto_now=True)),
                ('createuser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_projattachments', to=settings.AUTH_USER_MODEL)),
                ('deleteuser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_projattachments', to=settings.AUTH_USER_MODEL)),
                ('lastmodifyuser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_projattachments', to=settings.AUTH_USER_MODEL)),
                ('proj', utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_attachment', to='proj.project')),
            ],
            options={
                'db_table': 'projectAttachment',
            },
        ),
    ]
