# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-08 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0019_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('admin_addproj', '\u7ba1\u7406\u5458\u4e0a\u4f20\u9879\u76ee'), ('admin_changeproj', '\u7ba1\u7406\u5458\u4fee\u6539\u9879\u76ee'), ('admin_deleteproj', '\u7ba1\u7406\u5458\u5220\u9664\u9879\u76ee'), ('admin_getproj', '\u7ba1\u7406\u5458\u67e5\u770b\u9879\u76ee'), ('user_addproj', '\u7528\u6237\u4e0a\u4f20\u9879\u76ee'), ('user_changeproj', '\u7528\u6237\u4fee\u6539\u9879\u76ee(obj\u7ea7\u522b)'), ('user_deleteproj', '\u7528\u6237\u5220\u9664\u9879\u76ee(obj\u7ea7\u522b)'), ('user_getproj', '\u7528\u6237\u67e5\u770b\u9879\u76ee(obj\u7ea7\u522b)'))},
        ),
    ]
