# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-14 13:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0018_charactertype'),
        ('proj', '0020_auto_20170608_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='character',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u6211\u7684\u89d2\u8272', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.CharacterType'),
        ),
    ]
