# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-19 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0021_project_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='createtime',
            new_name='createdtime',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='deletetime',
            new_name='deletedtime',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='deleteuser',
            new_name='deleteduser',
        ),
        migrations.RenameField(
            model_name='finance',
            old_name='createtime',
            new_name='createdtime',
        ),
        migrations.RenameField(
            model_name='finance',
            old_name='deletetime',
            new_name='deletedtime',
        ),
        migrations.RenameField(
            model_name='finance',
            old_name='deleteuser',
            new_name='deleteduser',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='createtime',
            new_name='createdtime',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='deletetime',
            new_name='deletedtime',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='deleteuser',
            new_name='deleteduser',
        ),
    ]
