# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0022_auto_20170619_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='createdtime',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='favoriteproject',
            name='createdtime',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finance',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='createdtime',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
