# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0023_auto_20170619_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='createdtime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favoriteproject',
            name='createdtime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='createdtime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectindustries',
            name='createdtime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttags',
            name='createdtime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttransactiontype',
            name='createdtime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
