# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-26 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj', '0026_auto_20170621_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('admin_addproj', '\u7ba1\u7406\u5458\u4e0a\u4f20\u9879\u76ee'), ('admin_changeproj', '\u7ba1\u7406\u5458\u4fee\u6539\u9879\u76ee'), ('admin_deleteproj', '\u7ba1\u7406\u5458\u5220\u9664\u9879\u76ee'), ('admin_getproj', '\u7ba1\u7406\u5458\u67e5\u770b\u9879\u76ee'), ('user_addproj', '\u7528\u6237\u4e0a\u4f20\u9879\u76ee'), ('user_changeproj', '\u7528\u6237\u4fee\u6539\u9879\u76ee(obj\u7ea7\u522b)'), ('user_deleteproj', '\u7528\u6237\u5220\u9664\u9879\u76ee(obj\u7ea7\u522b)'), ('user_getproj', '\u7528\u6237\u67e5\u770b\u9879\u76ee(obj\u7ea7\u522b)'), ('get_secretinfo', '\u67e5\u770b\u4fdd\u5bc6\u4fe1\u606f'))},
        ),
        migrations.AddField(
            model_name='project',
            name='makeUser',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u627f\u505a\u4eba', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermake_projs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='takeUser',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u627f\u63fd\u4eba', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertake_projs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='supportUser',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u4e0a\u4f20\u4eba', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersupport_projs', to=settings.AUTH_USER_MODEL),
        ),
    ]
