# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-20 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0028_auto_20170629_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ismarketplace',
            field=models.BooleanField(default=False, help_text='\u662f\u5426\u662fmarketplace'),
        ),
        migrations.AddField(
            model_name='project',
            name='linkpdfkey',
            field=models.TextField(blank=True, help_text='marketplace\u94fe\u63a5pdf\u6587\u4ef6', null=True),
        ),
    ]
