# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-25 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0029_auto_20170720_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='supportUser',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u9879\u76ee\u65b9(\u4e0a\u4f20\u65b9)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersupport_projs', to=settings.AUTH_USER_MODEL),
        ),
    ]
