# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-25 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0030_auto_20170725_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isSend',
            field=models.BooleanField(default=False, help_text='\u662f\u5426\u53d1\u9001\u90ae\u4ef6'),
        ),
    ]
