# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-25 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0031_project_issend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproject',
            options={'ordering': ('proj',), 'permissions': (('admin_addfavorite', '\u7ba1\u7406\u5458\u6dfb\u52a0favorite'), ('admin_getfavorite', '\u7ba1\u7406\u5458\u67e5\u770bfavorite'), ('admin_deletefavorite', '\u7ba1\u7406\u5458\u5220\u9664favorite'))},
        ),
    ]
