# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-26 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0032_auto_20170725_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='isSend',
            new_name='isSendEmail',
        ),
        migrations.AddField(
            model_name='project',
            name='publishDate',
            field=models.DateTimeField(blank=True, help_text='\u7ec8\u5ba1\u53d1\u5e03\u65e5\u671f', null=True),
        ),
    ]
