# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-02 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sourcetype', '0022_auto_20170802_1059'),
        ('proj', '0033_auto_20170726_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='projServices',
            fields=[
                ('createdtime', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createuser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_projservices', to=settings.AUTH_USER_MODEL)),
                ('deleteduser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_projservices', to=settings.AUTH_USER_MODEL)),
                ('proj', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_services', to='proj.project')),
                ('service', utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_projects', to='sourcetype.Service')),
            ],
            options={
                'db_table': 'proj_services',
            },
        ),
    ]
