# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-02 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0034_projservices'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projservices',
            table='project_services',
        ),
    ]
