# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0023_auto_20170802_1407'),
        ('proj', '0036_auto_20170802_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ManyToManyField(blank=True, through='proj.projServices', to='sourcetype.Service'),
        ),
    ]
