# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-08 11:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0037_project_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projstatus',
            field=utils.customClass.MyForeignKey(default=2, help_text='\u9879\u76ee\u72b6\u6001', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.ProjectStatus'),
        ),
    ]
