# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-06 18:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0039_auto_20170808_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=utils.customClass.MyForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcetype.CurrencyType'),
        ),
    ]
