# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titleC', models.CharField(blank=True, max_length=128, null=True)),
                ('titleE', models.TextField(blank=True, null=True)),
                ('bucket', models.CharField(max_length=16)),
                ('key', models.CharField(max_length=64)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('detailUrl', models.URLField()),
                ('isActive', models.BooleanField(default=True)),
                ('isNews', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('lastmodifytime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
    ]
