# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20170412_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='createuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='deleteduser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userdelete_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lastmodifyuser',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermodify_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
