# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-06 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20170713_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='bucket',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='detailUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lastmodifytime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
