# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=16)),
                ('nameE', models.CharField(max_length=128)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=16)),
                ('nameE', models.CharField(max_length=128)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('continentC', models.CharField(max_length=16)),
                ('continentE', models.CharField(max_length=32)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('countryC', models.CharField(max_length=16)),
                ('countryE', models.CharField(max_length=32)),
                ('areaCode', models.CharField(max_length=8)),
                ('isdeleted', models.BooleanField(default=False)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', related_query_name='continent', to='sourcetype.Continent')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currencyC', models.CharField(max_length=16)),
                ('currencyE', models.CharField(max_length=8)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=16)),
                ('nameE', models.CharField(max_length=128)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Pindustry', models.SmallIntegerField()),
                ('industryC', models.CharField(max_length=16)),
                ('industryE', models.CharField(max_length=32)),
                ('bucket', models.CharField(max_length=8)),
                ('key', models.CharField(max_length=64)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=16)),
                ('nameE', models.CharField(max_length=128)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrgArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=16)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrgType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=16)),
                ('nameE', models.CharField(max_length=128)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=16)),
                ('nameE', models.CharField(max_length=128)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.TextField(blank=True, default='\u65e0')),
                ('nameE', models.TextField(blank=True, default='none')),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.TextField(blank=True, default='\u65e0')),
                ('nameE', models.TextField(blank=True, default='none')),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=16)),
                ('nameE', models.CharField(max_length=16)),
                ('hotpoint', models.SmallIntegerField(blank=True, default=0)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TitleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=16)),
                ('nameE', models.CharField(max_length=128)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPhases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=16)),
                ('nameE', models.CharField(max_length=32)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=16)),
                ('nameE', models.CharField(max_length=32)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=16)),
                ('nameE', models.CharField(max_length=32)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
