# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-20 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0002_auto_20170419_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgarea',
            name='nameE',
            field=models.CharField(default='no nameE', max_length=16),
            preserve_default=False,
        ),
    ]
