# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-10 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0003_orgarea_namee'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='bucket',
            field=models.CharField(blank=True, default='image', max_length=8),
        ),
        migrations.AddField(
            model_name='country',
            name='key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='bucket',
            field=models.CharField(blank=True, default='image', max_length=8),
        ),
    ]
