# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-15 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0007_auto_20170515_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgarea',
            old_name='isdeleted',
            new_name='is_deleted',
        ),
    ]
