# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-17 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0008_auto_20170515_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstatus',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
