# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-19 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0009_transactionstatus_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', related_query_name='continent', to='sourcetype.Continent'),
        ),
    ]
