# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-22 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0010_auto_20170519_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namekey', models.CharField(blank=True, max_length=32, null=True)),
                ('uri', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, help_text='\u56fe\u6807\u94fe\u63a5', max_length=64, null=True)),
            ],
            options={
                'permissions': (('orgmanage', '\u673a\u6784\u7ba1\u7406'), ('emailmanage', '\u90ae\u4ef6\u7ba1\u7406'), ('timelinemanage', '\u65f6\u95f4\u8f74\u7ba1\u7406'), ('usermanage', '\u4f1a\u5458\u7ba1\u7406'), ('dataroommanage', 'dataroom\u7ba1\u7406'), ('myinvestor', '\u6211\u7684\u6295\u8d44\u4eba'), ('mytrader', '\u6211\u7684\u4ea4\u6613\u5e08'), ('msgcenter', '\u6d88\u606f\u4e2d\u5fc3'), ('usercenter', '\u4e2a\u4eba\u4e2d\u5fc3'), ('changepwd', '\u4fee\u6539\u5bc6\u7801'), ('personalinfo', '\u4e2a\u4eba\u4fe1\u606f'), ('logcheck', '\u65e5\u5fd7\u67e5\u8be2'), ('projmanage', '\u9879\u76ee\u7ba1\u7406'), ('postproj', '\u53d1\u5e03\u9879\u76ee'), ('projlist', '\u5e73\u53f0\u9879\u76ee')),
            },
        ),
    ]
