# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0011_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='webmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namekey', models.CharField(blank=True, max_length=32, null=True)),
                ('uri', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, help_text='\u56fe\u6807\u94fe\u63a5', max_length=64, null=True)),
                ('parentmenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.webmenu')),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='menu',
        ),
    ]
