# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0012_auto_20170522_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webmenu',
            options={},
        ),
        migrations.AlterField(
            model_name='webmenu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
