# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0013_auto_20170523_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmenu',
            name='parentmenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pmenu_Smenus', to='sourcetype.webmenu'),
        ),
    ]
