# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0014_auto_20170523_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webmenu',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='webmenu',
            name='uri',
        ),
        migrations.AddField(
            model_name='webmenu',
            name='icon_active',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='webmenu',
            name='icon_normal',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
