# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0015_auto_20170523_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmenu',
            name='index',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
