# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 17:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0016_webmenu_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', related_query_name='continent', to='sourcetype.Continent'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='Pindustry',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u7236\u7ea7\u884c\u4e1a', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pindustry_Sindustries', to='sourcetype.Industry'),
        ),
        migrations.AlterField(
            model_name='webmenu',
            name='parentmenu',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pmenu_Smenus', to='sourcetype.webmenu'),
        ),
    ]
