# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0017_auto_20170605_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('characterC', models.CharField(max_length=20)),
                ('characterE', models.CharField(max_length=128)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
