# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-21 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0018_charactertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='orgtitletable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleindex', models.PositiveSmallIntegerField(blank=True, default=0, help_text='\u804c\u4f4d\u6743\u91cd')),
                ('orgtype', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.OrgType')),
                ('title', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.TitleType')),
            ],
        ),
    ]
