# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0019_orgtitletable'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgtitletable',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webmenu',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
