# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-02 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0022_auto_20170802_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='datasource',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='tag',
            name='datasource',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
