# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-07 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0023_auto_20170802_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='datasource',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
