# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-08 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0024_country_datasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industryC',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='industryE',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
