# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-07 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0025_auto_20170808_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attributeC', models.CharField(blank=True, max_length=32, null=True)),
                ('attributeE', models.CharField(blank=True, max_length=128, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
