# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIlog', '0002_auto_20170517_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPaddress', models.CharField(blank=True, max_length=32, null=True)),
                ('URL', models.CharField(blank=True, max_length=128, null=True)),
                ('method', models.CharField(blank=True, max_length=16, null=True)),
                ('requestbody', models.TextField()),
                ('requestuser', models.IntegerField(blank=True, null=True)),
                ('modeltype', models.CharField(blank=True, max_length=32, null=True)),
                ('modelID', models.IntegerField(blank=True, null=True)),
                ('request_before', models.TextField(blank=True, null=True)),
                ('request_after', models.TextField(blank=True, null=True)),
                ('actiontime', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('datasource', models.PositiveSmallIntegerField(blank=True, default=1)),
            ],
            options={
                'db_table': 'API_LOG',
            },
        ),
        migrations.AddField(
            model_name='loginlog',
            name='datasource',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='userviewprojlog',
            name='datasource',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userviewprojlog',
            name='proj',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userviewprojlog',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
