# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIlog', '0003_auto_20170523_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginlog',
            old_name='loginsource',
            new_name='logintype',
        ),
    ]
