# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-06 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIlog', '0004_auto_20170523_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apilog',
            old_name='requestuser',
            new_name='requestuserid',
        ),
        migrations.AddField(
            model_name='apilog',
            name='modelName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apilog',
            name='requestusername',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
