# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-25 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIlog', '0006_auto_20170606_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='ipadress',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
