# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-25 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIlog', '0007_loginlog_ipadress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginlog',
            old_name='ipadress',
            new_name='ipaddress',
        ),
    ]
