# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-15 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIlog', '0008_auto_20170725_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfoupdatelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('user_name', models.CharField(blank=True, max_length=64, null=True)),
                ('before', models.CharField(blank=True, max_length=128, null=True)),
                ('after', models.CharField(blank=True, max_length=128, null=True)),
                ('requestuser_id', models.IntegerField(blank=True, null=True)),
                ('requestuser_name', models.CharField(blank=True, max_length=64, null=True)),
                ('updatetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('datasource', models.PositiveSmallIntegerField(blank=True, default=1)),
            ],
            options={
                'db_table': 'LOG_userinfoupdate',
            },
        ),
    ]
