# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import sourcetype.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u7ad9\u5185\u4fe1\u8be6\u7ec6\u5185\u5bb9')),
                ('type', models.IntegerField(default=1, verbose_name=sourcetype.models.MessageType)),
                ('title', models.CharField(max_length=128, verbose_name='\u6d88\u606f\u6807\u9898')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('isread', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8bfb')),
            ],
            options={
                'db_table': 'msg',
            },
        ),
    ]
