# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-10 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcetype', '0006_auto_20170510_1045'),
        ('msg', '0002_auto_20170412_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datasource',
            field=models.ForeignKey(default=1, help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userreceive_msgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
