# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0004_auto_20170524_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datasource',
            field=utils.customClass.MyForeignKey(help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_deleted',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=utils.customClass.MyForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userreceive_msgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersend_msgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
