# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-25 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0005_auto_20170605_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='isread',
            new_name='isRead',
        ),
        migrations.AddField(
            model_name='message',
            name='readtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
