# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-27 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('msg', '0006_auto_20170725_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sourceid',
            field=models.IntegerField(blank=True, help_text='\u5173\u8054\u8d44\u6e90id', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sourcetype',
            field=utils.customClass.MyForeignKey(blank=True, help_text='\u5173\u8054\u8d44\u6e90\u7c7b\u578b', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
