# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-28 15:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sourcetype.models
import utils.customClass


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0007_auto_20170727_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='\u7ad9\u5185\u4fe1\u8be6\u7ec6\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='message',
            name='datasource',
            field=utils.customClass.MyForeignKey(blank=True, default=1, help_text='\u6570\u636e\u6e90', on_delete=django.db.models.deletion.CASCADE, to='sourcetype.DataSource'),
        ),
        migrations.AlterField(
            model_name='message',
            name='messagetitle',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u6d88\u606f\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userreceive_msgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(blank=True, default=1, verbose_name=sourcetype.models.MessageType),
        ),
    ]
