# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-22 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.customClass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0038_organization_managername'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj', '0047_auto_20171122_1129'),
        ('sourcetype', '0032_templatesign_webmsg_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgBD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('username', models.CharField(blank=True, help_text='\u59d3\u540d', max_length=64, null=True)),
                ('usermobile', models.CharField(blank=True, help_text='\u7535\u8bdd', max_length=64, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('datasource', models.IntegerField(blank=True, null=True)),
                ('bd_status', utils.customClass.MyForeignKey(blank=True, help_text='bd\u72b6\u6001', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.BDStatus')),
                ('createuser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_OrgBD', to=settings.AUTH_USER_MODEL)),
                ('deleteduser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_OrgBD', to=settings.AUTH_USER_MODEL)),
                ('manager', utils.customClass.MyForeignKey(blank=True, help_text='\u8d1f\u8d23\u4eba', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('org', utils.customClass.MyForeignKey(blank=True, help_text='BD\u673a\u6784', null=True, on_delete=django.db.models.deletion.CASCADE, to='org.organization')),
                ('proj', utils.customClass.MyForeignKey(blank=True, help_text='\u9879\u76ee\u540d\u79f0', null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.project')),
                ('usertitle', utils.customClass.MyForeignKey(blank=True, help_text='\u804c\u4f4d', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.TitleType')),
            ],
            options={
                'permissions': (('manageOrgBD', '\u7ba1\u7406\u9879\u76eeBD'), ('getOrgBD', '\u67e5\u770b\u9879\u76eeBD')),
            },
        ),
        migrations.CreateModel(
            name='OrgBDComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('comments', models.TextField(blank=True, default=False, help_text='\u5185\u5bb9')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('datasource', models.IntegerField(blank=True, null=True)),
                ('createuser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_OrgBDComments', to=settings.AUTH_USER_MODEL)),
                ('deleteduser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_OrgBDComments', to=settings.AUTH_USER_MODEL)),
                ('orgBD', utils.customClass.MyForeignKey(blank=True, help_text='\u673a\u6784BD', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrgBD_comments', to='BD.OrgBD')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('com_name', models.TextField(blank=True, help_text='\u516c\u53f8\u540d\u79f0/\u9879\u76ee\u540d\u79f0', null=True)),
                ('username', models.CharField(blank=True, help_text='\u59d3\u540d', max_length=64, null=True)),
                ('usermobile', models.CharField(blank=True, help_text='\u7535\u8bdd', max_length=64, null=True)),
                ('source', models.TextField(blank=True, help_text='\u6765\u6e90', null=True)),
                ('source_type', models.IntegerField(blank=True, choices=[(0, '\u5168\u5e93\u641c\u7d22'), (1, '\u5176\u4ed6')], null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('datasource', models.IntegerField(blank=True, null=True)),
                ('bd_status', utils.customClass.MyForeignKey(blank=True, help_text='bd\u72b6\u6001', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.BDStatus')),
                ('createuser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_ProjectBD', to=settings.AUTH_USER_MODEL)),
                ('deleteduser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_ProjectBD', to=settings.AUTH_USER_MODEL)),
                ('location', utils.customClass.MyForeignKey(blank=True, help_text='\u9879\u76ee\u5730\u533a', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.Country')),
                ('manager', utils.customClass.MyForeignKey(blank=True, help_text='\u8d1f\u8d23\u4eba', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usertitle', utils.customClass.MyForeignKey(blank=True, help_text='\u804c\u4f4d', null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcetype.TitleType')),
            ],
            options={
                'permissions': (('manageProjectBD', '\u7ba1\u7406\u9879\u76eeBD'), ('getProjectBD', '\u67e5\u770b\u9879\u76eeBD')),
            },
        ),
        migrations.CreateModel(
            name='ProjectBDComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('comments', models.TextField(blank=True, default=False, help_text='\u5185\u5bb9')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletedtime', models.DateTimeField(blank=True, null=True)),
                ('datasource', models.IntegerField(blank=True, null=True)),
                ('createuser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreate_ProjectBDComments', to=settings.AUTH_USER_MODEL)),
                ('deleteduser', utils.customClass.MyForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdelete_ProjectBDComments', to=settings.AUTH_USER_MODEL)),
                ('projectBD', utils.customClass.MyForeignKey(blank=True, help_text='bd\u9879\u76ee', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectBD_comments', to='BD.ProjectBD')),
            ],
        ),
    ]
